#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.


COUNTER=0
while [ "$COUNTER" -lt 10 ]; do
	echo "Best School"
	if [ "$COUNTER" -eq 8 ]
	then
	    echo "Hi"
	fi
	let COUNTER=COUNTER+1
done